pip install -U Brotli
pip install -U PyAudio
pip install -U SpeechRecognition
pip install -U aiohttp
pip install -U aiosignal
pip install -U attrs
pip install -U certifi
pip install -U cffi
pip install -U charset-normalizer
pip install -U click
pip install -U colorama
pip install -U curl-cffi
pip install -U distutils-pytest
pip install -U dnspython
pip install -U eventlet
pip install -U frozenlist
pip install -U Flask
pip install -U g4f
pip install -U gTTS
pip install -U idna
pip install -U iniconfig
pip install -U multidict
pip install -U numpy
pip install -U packaging
pip install -U pluggy
pip install -U pycparser
pip install -U pycryptodome
pip install -U pytest
pip install -U requests
pip install -U setuptools
pip install -U sounddevice
pip install -U soundfile
pip install -U typing-extensions
pip install -U urllib3
pip install -U yarl